### ISSUE TITLE
Error when trying to login with f2a.

### ISSUE THREAD

**Issue by johndongus** [matias-kovero/tarkov#10]
Using the example code found here, at
 `let t = await tarkov.login_with_2fa`

T is returning as undefined. Am i doing something wrong?

**Comment by matias-kovero** [comment]
You are trying to use the function like:
`
let t = await tarkov.login_with_2fa("username@domain.com", "p@assw0rd", "2FACode", "yourHWID");
`
or a different way?

**Comment by devolution2409** [comment]
I'm getting the same, t seems to be undefined
```
207 - Wrong parameters
(node:211) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'session' of undefined
    at /source/build/index.js:45:60
    at step (/source/node_modules/tslib/tslib.js:136:27)
    at Object.next (/source/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/source/node_modules/tslib/tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I modified auth.js because the thrown error wasn't correct, it was `throw new Error(errmsg)` when i think it should have been `throw new error (res.errmsg)`

which is how i got the 207 error

I tried modifying the POST params to be device_id instead of hwid, now i get 211 wrong activation code. Not sure if its the correcct post param to send, or if it will always throw 211 becaue it's not

**Comment by matias-kovero** [comment]
Fixing this currently, will try to post update today

**Comment by johndongus** [comment]
Yes after changing the inputs in the index.js file i had success.

**Comment by matias-kovero** [comment]
> Yes after changing the inputs in the index.js file i had success.

You are able to complete the 2FA? Currently getting wrong 2FA code error

**Comment by johndongus** [comment]
So yes, I am also currently getting a f2a error, but im still logged in and everything is working as epected. But i get the 211 error every time i start a new session

Which on that topic, how often can i make new sessions (where i wont get caught)

**Comment by johndongus** [comment]
are you still able to send API requests? I am even with the 211

> I'm getting the same, t seems to be undefined
> 
> ```
> 207 - Wrong parameters
> (node:211) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'session' of undefined
>     at /source/build/index.js:45:60
>     at step (/source/node_modules/tslib/tslib.js:136:27)
>     at Object.next (/source/node_modules/tslib/tslib.js:117:57)
>     at fulfilled (/source/node_modules/tslib/tslib.js:107:62)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```
> 
> I modified auth.js because the thrown error wasn't correct, it was `throw new Error(errmsg)` when i think it should have been `throw new error (res.errmsg)`
> 
> which is how i got the 207 error
> 
> I tried modifying the POST params to be device_id instead of hwid, now i get 211 wrong activation code. Not sure if its the correcct post param to send, or if it will always throw 211 becaue it's not

I am also getting the 211 error, but im still able to send api requests successfully.

**Comment by matias-kovero** [comment]
> I am also getting the 211 error, but im still able to send api requests successfully.

Could you provide your code you are using? As on my testing currently I get 211, and unable to send any requests.

**Comment by johndongus** [comment]
> > I am also getting the 211 error, but im still able to send api requests successfully.
> 
> Could you provide your code you are using? As on my testing currently I get 211, and unable to send any requests.

I am currently just using the example code given on the npm page. Wrapped in a async function.
I spent alot of time authenticating over and over again until it worked.

But here is a snippet:
`global.t = await tarkov.login_with_2fa("EMAIL", "PASS", "CODE", hwid);
const intervalObj = setInterval(async () => {

    if(requests > 5){
        global.t = await tarkov.login_with_2fa("EMAIL", "PASS", "CODE", hwid);
        console.log('Reloaded session '+t.session)
        requests = 0
    }
  }, 2000);`

I also changed the login with 2fa prototype to "await auth.activate_hardware(this.client, email, code, hwid);"  , not sure if thats changed from original but thats what im using

also im printing out the err obj since errormsg was not defined

**Comment by CodeWithBryan** [comment]
I also am only getting 211 on 2fa auth after making the changes above

**Comment by CodeWithBryan** [comment]
> I spent alot of time authenticating over and over again until it worked.

> `global.t = await tarkov.login_with_2fa("EMAIL", "PASS", "CODE", hwid);
> const intervalObj = setInterval(async () => {
> 
> ```
> if(requests > 5){
>     global.t = await tarkov.login_with_2fa("EMAIL", "PASS", "CODE", hwid);
>     console.log('Reloaded session '+t.session)
>     requests = 0
> }
> ```
> 
> }, 2000);`

What is `requests` in this? Are you trying to get a new session after 5 API requests?

**Comment by johndongus** [comment]
> > I spent alot of time authenticating over and over again until it worked.
> 
> > `global.t = await tarkov.login_with_2fa("EMAIL", "PASS", "CODE", hwid);
> > const intervalObj = setInterval(async () => {
> > ```
> > if(requests > 5){
> >     global.t = await tarkov.login_with_2fa("EMAIL", "PASS", "CODE", hwid);
> >     console.log('Reloaded session '+t.session)
> >     requests = 0
> > }
> > ```
> > 
> > 
> > }, 2000);`
> 
> What is `requests` in this? Are you trying to get a new session after 5 API requests?

yeah its just a counter where i am resetting the session every 5 *searches*

**Comment by matias-kovero** [comment]
You should really just need 1 session, no need to reset sessions. And if +20sec idle on session, send keep_alive().  
Currently totally lost with the 2FA part.
Fixed all typos etc, on the 2FA part, now it send you the code to your email, when you use new hwid. But if you use login_with_2fa with the code it will return 211.

Spamming request to create new session isn't the right way to fix this issue. 

Need to get in hold with a new account that I could get a new hwid request, so I could log the packets. Or just info on how to remove my current HWID from my account would also work.

**Not really sure where you got the device_id, but updated the api to use it...** (still gives 211)

Info ripped from launhcer. 
```C#
[JsonProperty(PropertyName = "email")]
internal string Email { get; set; }

[JsonProperty(PropertyName = "hwCode")]
internal string HardwareId { get; set; }

[JsonProperty(PropertyName = "activateCode")]
internal string ActivationCode { get; set; }

internal HardwareActivationRequestData(string email, string hardwareId, string activationCode)
{
	this.Email = email;
	this.HardwareId = hardwareId;
	this.ActivationCode = activationCode;
}
```

**Comment by CodeWithBryan** [comment]
@matias-kovero Just send a new request with a newly generate HWID using you current account

I'll look at the packets going out and see what I can find

**Comment by CodeWithBryan** [comment]
I've gotten it working, I'm going to make a PR now.

**Comment by johndongus** [comment]
I pushed the change to my project, Now im getting a error with session not existing. (havent changed any code on my end) Aswell as 2fa code not being correct, which im pretty sure it is.

**Comment by CodeWithBryan** [comment]
Try logging in to the account through the launcher manually, you probably need to solve a captcha

**Comment by johndongus** [comment]
Logged in manually, No captcha, and didnt ask for 2fa, still the same issue though

**Comment by matias-kovero** [comment]
@bryandesigning Going to check the PR soon. Nice work.

Debugged the launcher to use one of my generated IDs. It gives also 211
![7223e6396b75c76730e1d72cb78edd7b](https://user-images.githubusercontent.com/47692525/74786080-86f4c300-52b4-11ea-87be-7eb0eefa38ce.png)

**Comment by CodeWithBryan** [comment]
That's super strange.... With the changes I have in the PR it's working 100% for me, unless I need captcha solved.

**Comment by matias-kovero** [comment]
@bryandesigning you used my generate_hwid function? Could you check how long each hash is in the hwid? Char length between - characters.

Is it 32 or 40

**Comment by CodeWithBryan** [comment]
> @bryandesigning you used my generate_hwid function? Could you check how long each hash is in the hwid? Char length between - characters.
> 
> Is it 32 or 40

Yes, using your old method (before you changed in ~3 hours ago)
#1-[32]:[32]:[32]-[32]-[32]-[32]-[24]

that's what the HWID looks like, digits being the number of chars.

**Comment by matias-kovero** [comment]
Launcher uses SHA1 on its HWIDs

so thats why I changed it:
#1-[40]:[40]:[40]-[40]-[40]-[40]-[32]

You can verify this by sniffing a legit HWID with Fiddler from the launcher

**Comment by johndongus** [comment]
Yes, after updating it again i now cannot seem to get it to function at all. Correct HWID and 2fa aswell.

Should i generate a new HWID?
