### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by mikkel-ol** [matias-kovero/tarkov#11]
Will the incrementor header be implemented?

**Comment by matias-kovero** [comment]
As soon as I get a valid source that the header `GClient-RequestId` is the right header to add.

Still having issues parsing strings from current gamefiles. If anyone knows how to get strings to show on dnSpy, please inform me.

**Comment by wallopthecat** [comment]
I can help you with strings - are you looking in Assembly-CSharp.dll?

GClient-RequestId is the proper header iirc, and it increments by 1 every API call, starting from 1 after login

**Comment by matias-kovero** [comment]
When the .ts version is ready it will have this header

**Comment by matias-kovero** [comment]
Added on version 1.0.0
