### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by CodeWithBryan** [matias-kovero/tarkov#15]
Can we get a discord server to chat about new features/etc?

I'd like to help rewrite this in typescript, just don't wanna rewrite the whole thing if you don't want it haha

**Comment by wallopthecat** [comment]
TS would be a welcome addition imo

**Comment by CodeWithBryan** [comment]
Yeah, I've already started on a branch in my fork, will be pushing up the starting framework later tonight

**Comment by matias-kovero** [comment]
@bryandesigning Created Discord: [Join](https://discord.gg/aQPAUCJ)

Had a TS version already, but had issues with documentation frameworks. Will check your version and review it.

In the long run it would be perfect to get this to TS.

###### Ps. Discord currently at barebones - just created. Will customize it when I have more time.
