### ISSUE TITLE
How do i enter the captcha when authenticating using new hwid?

### ISSUE THREAD

**Issue by rikato** [matias-kovero/tarkov#2]
I am using a new hwid and I have to enter the captcha but how do I solve the capthca without seeing it. Can i load the captcha in some sort of ui and solve it that way?

**Comment by rikato** [comment]
Trying to use the captcha harvester but need the SiteKey and Solve URL. You know these parameters perhaps?

**Comment by EgorHenek** [comment]
> Trying to use the captcha harvester but need the SiteKey and Solve URL. You know these parameters perhaps?

URL: https://launcher.escapefromtarkov.com/launcher/login
Site_key: 6LexEI4UAAAAAIFtNZALcloZfEgHhB8rEUqC1LwV

**Comment by rikato** [comment]
Thanks
