### ISSUE TITLE
Missing param "quantity" in Tarkov.prototype.move_item

### ISSUE THREAD

**Issue by config-old** [matias-kovero/tarkov#27]
My English is bad, but i hope you understand.

The `Tarkov.prototype.stack_item` only Works if the two stracks together don't get a higher value than the Maximum stack size.
For example a Stack of 250001 Rouble and a Stack 250000 Rouble can not be merged. (In my case)

So you can modify `Tarkov.prototype.move_item` and add `quantity: amount,` into the `body = { ...}`.
This way you can perfectly merge and split stacks.

Please tell me if i am wrong.

**Comment by matias-kovero** [comment]
@P1koOCod3 thanks for pointing out. Will add this to the new version.

**Comment by config-old** [comment]
I write a merge function soon so I can put it inside this topic.
