### ISSUE TITLE
offerItem bad count in requirements

### ISSUE THREAD

**Issue by samuelkampf** [matias-kovero/tarkov#28]
im getting a bad count in requirements errors when attempting todo offer item here is my code snippet any help or clarification of what im doing wrong here would be great or if you could provide me an example thanks.

```
         await t.offerItem(['5e546ceecc540568211bb51a'],{ _tpl: '59e35cbb86f7741778269d83',
            count: '35000'}).then(item => {
             console.log(item)
         }).catch(error => {
             console.log(error)
         })
    }
  })
```

**Comment by samuelkampf** [comment]
ohhh it should be price not count

**Comment by config-old** [comment]
what is `59e35cbb86f7741778269d83`?
When u need rouble than: use this: `const rub_id = '5449016a4bdc2d6f028b456f';`

**Comment by matias-kovero** [comment]
Please check your IDs,

```js
await t.offerItem(items, requiments, sellAll?);
```
items = _Array of item ids you are selling_
requiments<Object> (_tpl, price)
sellAll(Optional) = _Sell all in one piece. Default = false._

`59e35cbb86f7741778269d83` is the ID of **Hose**
View docs: [offerItem](https://matias-kovero.github.io/tarkov/classes/tarkov.tarkov-2.html#offeritem)

**Comment by samuelkampf** [comment]
yeah i had figured it out sorry i forgot to close the issue
