### ISSUE TITLE
keep_alive method not fully implemented

### ISSUE THREAD

**Issue by bpluhar** [matias-kovero/tarkov#4]
keep_alive method within Tarkov is not fully implemented, I can see you began implementation but currently have it commented out on Line 206 of index.js

**Comment by matias-kovero** [comment]
Implementing this to the next version 👍

**Comment by bpluhar** [comment]
Thank you! Upon adding it myself into index.js using

```js
Tarkov.prototype.keep_alive = async function() {
  try {
    let url = `https://${PROD_ENDPOINT}/client/game/keepalive`;
    let res = await this.post_json(url, {});
    console.log(res);
  } catch (error) {
    throw new Error(error.message);
  }
}
```
Upon each call `post_json()` returns a 201 saying "Client not authorized or not selected game profile". I run the function after logged in and profile (pmc) selection. I'm assuming this is simply due to you having to do some work in other places too and it not being as simple as adding a method like I did.

I'll wait patiently for your update!

**Comment by matias-kovero** [comment]
@bpluhar Thanks for the additional information🎉. I'll need look closer what is causing the issue.

**Edit.**
Couldn't replicate your errors, and the code returned valid response from BSG servers.
