### ISSUE TITLE
Error "201 - Client not authorized or not selected game profile"

### ISSUE THREAD

**Issue by GiacomoBiagioni** [matias-kovero/tarkov#41]
I get this error when i start the bot while i'm in game and i thought that could be some problems with session (tarkov thinks you're using same account on 2 pc maybe?). You're having this problem too or is it just me? And you have some fixes?

P.S. I get this error in the bot too sometimes when i try to get the traders (with methods getTrader('id') and getTraders())

**Comment by CodeWithBryan** [comment]
This is super outdated and will almost 100% get you banned
