### ISSUE TITLE
getRoubles(), getEuros() and getDollars() all use rouble item id

### ISSUE THREAD

**Issue by bpluhar** [matias-kovero/tarkov#5]
Noticed you've declared roubles, euros and dollars with their ID's in `profile.js`, but their respected functions all utilize `rub_id` making all 3 methods return the same value 😄

**Comment by bpluhar** [comment]
Created PR here: https://github.com/matias-kovero/tarkov/pull/6

**Comment by matias-kovero** [comment]
Thanks, merged it in.
