### ISSUE TITLE
Any experience with this error? Error: 228 RagFairBuyOffer

### ISSUE THREAD

**Issue by rikato** [matias-kovero/tarkov#7]
Error: 228 - RagFairBuyOffer: Item 5e42xxxxxxxxxxxxx has count 70800, you send 90000

This error happens after buying items and selling them. But only when i'm doing it for a couple of minutes at the beginning it does not happen.

It has something to do with sending the wrong rouble count but I'm sending the right amount based on: {the offer}.requirementsCost.

**Comment by matias-kovero** [comment]
@rikato Seem like you are trying to buy with a item that doesn't have enough money on it. 
_You are trying to buy a 90 000 item with a money stack with only 70 800 money on it._

To solve this issue, just use a simple check: 
```javascript
/**
 * Returns a valid money stack with enough money
 */
async function get_valid_stack(amount) {
  let roubles = await profile.getRoubles(); // Or other currencies
  let stack = roubles.stacks.find(stack => stack.upd.StackObjectsCount > amount);
  if(!stack) throw Error('No stacks found! Do you have enough money?');
  return stack;
}
```
___
_Also when you are buying for a while, you need to keep your profiles inventory up-to-date._
Check: [Docs -> Profile](https://matias-kovero.github.io/tarkov/Profile.html#updateItems)

**Comment by rikato** [comment]
Yes I was already checking if I had enough money. But I was doing it without updating my profile inventory once every while. 

Thanks a lot for your help!
